theme: jekyll-theme-minimal
title: 📝
description: |
  🏠 Dubai, United Arab Emirates 🇦🇪
  <br/>
  <a href="tel: +971 50 637 2247">📱🇦🇪 +971 637 2247</a>
  <a href="tel:+33 7 82 33 53 54">📱🇫🇷 +33 7 82 33 53 54</a>
  <br/>
  <a href="mailto:salladiagne14@gmail.com">📧 salladiagne14@gmail.com</a>
  <br/>
  <a href="https://github.com/sallareznov">👨🏾‍💻 sallareznov</a>
  <br/>
  <a href="https://www.linkedin.com/in/salladiagne/">🖇️ LinkedIn</a>
  <br/>
